#!/bin/bash
#set -e


[ ! -e lista.txt ] && wget -q https://hu.wiktionary.org/wiki/Kateg%C3%B3ria:Magyar_szavak_list%C3%A1ja -O lista.txt

lista=$(
	cut -d\" -f2 lista.txt |
	grep /wiki/Index:Magyar/[a-z][a-z]*$ |
	sed s,^,https://hu.wiktionary.org,
)

for i in $lista
do
	betu=$(echo $i | sed "s,.*/,,")
	if [ ! -e betuk/$betu ]
	then
		valami=1
		echo -n "$betu " >&2
		wget -q $i -O betuk/$betu
	fi
done
[ -n "$valami" ] && echo

for i in betuk/*
do
	tr '<' '\n' <$i |
	grep -E '^a href="/w(iki/[a-z][a-z]+.*title=|.*a lap nem l)' |
	tr '>' '\n' |
	grep -v ^a.href |
	grep '^[a-z][a-z]*$'
done |
grep -vE '^(vissza|szerte|szembe|helyre|egybe|ellen|bele|haza|tele|neki|meg|fel|oda|ide)' |
cat; exit

awk 'length($0)>2 && length($0)<8' |
sort -k1.3 |
sed 7776q |
sort |
nl -v 0 |
while read number word
do
	base6=$(echo "obase=6; $number" | bc)
	printf "%05d %s\n" $base6 $word
done |
tr 5 6 |
tr 4 5 |
tr 3 4 |
tr 2 3 |
tr 1 2 |
tr 0 1 |
cat

# ./csinald | cut -c-3 | uniq -c | sort -nr | head
