#!/bin/bash
#set -e


[ ! -e lista.txt ] && wget -q https://hu.wiktionary.org/wiki/Kateg%C3%B3ria:Magyar_szavak_list%C3%A1ja -O lista.txt

lista=$(
	cut -d\" -f2 lista.txt |
	grep /wiki/Index:Magyar/[a-z][a-z]*$ |
	sed s,^,https://hu.wiktionary.org,
)

#echo "# Magyar Diceware lista"
#echo -n "# "

BETU_DIR=$(mktemp -d)
for i in $lista
do
	betu=$(echo $i | sed "s,.*/,,")
	echo -n "$betu "
	wget -q $i -O $BETU_DIR/$betu
done
echo

for i in $BETU_DIR/*
do
	tr '<' '\n' <$i |
	grep -E '^a href="/w(iki/[a-z][a-z]+.*title=|.*a lap nem l)' |
	tr '>' '\n' |
	grep -v ^a.href |
	grep '^[a-z][a-z]*$'
done |
grep -vE '^(vissza|szerte|szembe|helyre|egybe|ellen|bele|haza|tele|neki|meg|fel|oda|ide)' |
awk 'length($0)>2 && length($0)<8' |

#
# ezek használhatók teszteléskor
#
#wc -l; exit
#cut -c-2 | uniq -c | sort -nr | head; exit

sort -k1.3 |
sed 7776q |
sort |
nl -v 0 |
while read number word
do
	base6=$(echo "obase=6; $number" | bc)
	printf "%05d %s\n" $base6 $word
done |
tr 5 6 |
tr 4 5 |
tr 3 4 |
tr 2 3 |
tr 1 2 |
tr 0 1 |
cat
rm -rf $BETU_DIR
